package com.smartling.api.sdk.dto;

public enum ApiCode
{
    SUCCESS, VALIDATION_ERROR, AUTHENTICATION_ERROR, AUTHORIZATION_ERROR, RESOURCE_LOCKED, MAX_OPERATIONS_LIMIT_EXCEEDED, GENERAL_ERROR, MAINTENANCE_MODE_ERROR
}
