package com.smartling.api.sdk.file;

public class ResponseExamples
{
    public static final String UPLOAD_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "      \"code\": \"SUCCESS\",\n"
            + "      \"data\": {\n"
            + "   \"overWritten\": \"false\",\n"
            + "   \"stringCount\": \"1\",\n"
            + "   \"wordCount\": \"2\"\n"
            + "}\n"
            + "   }\n"
            + "}\n";
    public static final String EMPTY_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "      \"code\": \"SUCCESS\",\n"
            + "\"data\": {}\n"
            + "\n"
            + "}\n"
            + "}";
    public static final String LAST_MODIFICATION_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"totalCount\": 5,\n"
            + "      \"items\": [\n"
            + "        {\n"
            + "          \"localeId\": \"be-BY\",\n"
            + "          \"lastModified\": \"2015-09-15T21:24:42+0000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"zh-CN\",\n"
            + "          \"lastModified\": \"2015-09-15T21:24:42+0000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"it-IT\",\n"
            + "          \"lastModified\": \"2015-09-15T21:24:42+0000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"ru-RU\",\n"
            + "          \"lastModified\": \"2015-09-15T21:24:42+0000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"es\",\n"
            + "          \"lastModified\": \"2015-09-15T21:24:42+0000\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String GET_FILE_RESPONSE = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<contentItems>\n"
            + "    <value>test cancel translation</value>\n"
            + "</contentItems>";
    public static final String FILE_LIST_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"items\": [\n"
            + "        {\n"
            + "          \"fileUri\": \"3-namespace-explicit.xml\",\n"
            + "          \"lastUploaded\": \"2015-07-29T10:34:30+0000\",\n"
            + "          \"fileType\": \"xml\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"fileUri\": \"test-client-id.xml\",\n"
            + "          \"lastUploaded\": \"2015-08-11T17:31:48+0000\",\n"
            + "          \"fileType\": \"xml\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"totalCount\": 2\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String FILE_LOCALES_STATUS_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"fileUri\": \"test-cancel-translation.xml\",\n"
            + "      \"lastUploaded\": \"2015-09-15T21:28:25+0000\",\n"
            + "      \"fileType\": \"xml\",\n"
            + "      \"totalStringCount\": 1,\n"
            + "      \"totalWordCount\": 3,\n"
            + "      \"authorizedStringCount\": 0,\n"
            + "      \"authorizedWordCount\": 0,\n"
            + "      \"completedStringCount\": 0,\n"
            + "      \"completedWordCount\": 0,\n"
            + "      \"excludedStringCount\": 0,\n"
            + "      \"excludedWordCount\": 0\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String FILE_STATUS_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"fileUri\": \"test-cancel-translation.xml\",\n"
            + "      \"lastUploaded\": \"2015-09-15T21:28:25+0000\",\n"
            + "      \"fileType\": \"xml\",\n"
            + "      \"totalStringCount\": 1,\n"
            + "      \"totalWordCount\": 3,\n"
            + "      \"totalCount\": 5,\n"
            + "      \"items\": [\n"
            + "        {\n"
            + "          \"localeId\": \"be-BY\",\n"
            + "          \"authorizedStringCount\": 0,\n"
            + "          \"authorizedWordCount\": 0,\n"
            + "          \"completedStringCount\": 0,\n"
            + "          \"completedWordCount\": 0,\n"
            + "          \"excludedStringCount\": 0,\n"
            + "          \"excludedWordCount\": 0\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"es\",\n"
            + "          \"authorizedStringCount\": 1,\n"
            + "          \"authorizedWordCount\": 3,\n"
            + "          \"completedStringCount\": 0,\n"
            + "          \"completedWordCount\": 0,\n"
            + "          \"excludedStringCount\": 0,\n"
            + "          \"excludedWordCount\": 0\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"it-IT\",\n"
            + "          \"authorizedStringCount\": 1,\n"
            + "          \"authorizedWordCount\": 3,\n"
            + "          \"completedStringCount\": 0,\n"
            + "          \"completedWordCount\": 0,\n"
            + "          \"excludedStringCount\": 0,\n"
            + "          \"excludedWordCount\": 0\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"ru-RU\",\n"
            + "          \"authorizedStringCount\": 1,\n"
            + "          \"authorizedWordCount\": 3,\n"
            + "          \"completedStringCount\": 0,\n"
            + "          \"completedWordCount\": 0,\n"
            + "          \"excludedStringCount\": 0,\n"
            + "          \"excludedWordCount\": 0\n"
            + "        },\n"
            + "        {\n"
            + "          \"localeId\": \"zh-CN\",\n"
            + "          \"authorizedStringCount\": 0,\n"
            + "          \"authorizedWordCount\": 0,\n"
            + "          \"completedStringCount\": 0,\n"
            + "          \"completedWordCount\": 0,\n"
            + "          \"excludedStringCount\": 0,\n"
            + "          \"excludedWordCount\": 0\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String IMPORT_TRANSLATIONS_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"wordCount\": 0,\n"
            + "      \"stringCount\": 0,\n"
            + "      \"translationImportErrors\": []\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String FILE_AUTHORIZED_LOCALES_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"items\": [\n"
            + "        \"it-IT\",\n"
            + "        \"es\"\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}";
    public static final String FILE_AUTHORIZED_LOCALES_EXTRA_FIELDS_RESPONSE = "{\n"
            + "  \"response\": {\n"
            + "    \"code\": \"SUCCESS\",\n"
            + "    \"data\": {\n"
            + "      \"someNewField\": someNewValue,\n"
            + "      \"items\": [\n"
            + "        \"it-IT\",\n"
            + "        \"es\"\n"
            + "      ]\n"
            + "    }\n"
            + "  }\n"
            + "}";
}
